import { getTableColumns } from "drizzle-orm";
import type { PgTable } from "drizzle-orm/pg-core";
import {
  addons,
  adminUsers,
  categories,
  coupons,
  deliveryZones,
  homepageSections,
  inventoryItems,
  legalPages,
  media,
  menuItems,
  menuVariants,
  notifications,
  refunds,
  reservations,
  restaurantTables,
  reviews,
  roles,
  supportTickets,
  users,
} from "@/db/schema";

export type ResourceFieldType =
  | "text"
  | "textarea"
  | "number"
  | "money"
  | "boolean"
  | "select"
  | "date"
  | "datetime"
  | "image"
  | "permissions"
  | "password";

export type ResourceField = {
  key: string;
  label: string;
  type: ResourceFieldType;
  options?: { value: string; label: string }[];
  optionsFrom?: "categories" | "tables" | "roles" | "menu" | "drivers";
  required?: boolean;
  help?: string;
  inTable?: boolean;
  readOnly?: boolean;
  createOnly?: boolean;
};

export type ResourceDef = {
  key: string;
  label: string;
  singular: string;
  table: PgTable;
  group: string;
  viewPermission: string;
  managePermission: string;
  searchColumns: string[];
  orderBy: { column: string; dir: "asc" | "desc" };
  fields: ResourceField[];
  defaults: Record<string, unknown>;
  softDelete?: boolean;
  deletable?: boolean;
  creatable?: boolean;
  exportable?: boolean;
  moneyFields?: string[];
};

const ACTIVE = [
  { value: "true", label: "Active" },
  { value: "false", label: "Disabled" },
];

export const RESOURCES: ResourceDef[] = [
  {
    key: "categories",
    label: "Categories",
    singular: "Category",
    table: categories,
    group: "Menu",
    viewPermission: "menu.view",
    managePermission: "menu.edit",
    searchColumns: ["name", "slug"],
    orderBy: { column: "sortOrder", dir: "asc" },
    defaults: { isActive: true, prepTimeMinutes: 20, sortOrder: 0 },
    exportable: true,
    fields: [
      { key: "name", label: "Name", type: "text", required: true, inTable: true },
      { key: "slug", label: "Slug", type: "text", help: "Leave blank to auto-generate from name." },
      { key: "description", label: "Description", type: "textarea" },
      { key: "imageUrl", label: "Image", type: "image", inTable: true },
      { key: "prepTimeMinutes", label: "Prep time (min)", type: "number", inTable: true },
      { key: "sortOrder", label: "Sort order", type: "number", inTable: true },
      { key: "isActive", label: "Status", type: "select", options: ACTIVE, inTable: true },
      { key: "seoTitle", label: "SEO title", type: "text" },
      { key: "seoDescription", label: "SEO description", type: "textarea" },
    ],
  },
  {
    key: "menu-items",
    label: "Menu & dishes",
    singular: "Dish",
    table: menuItems,
    group: "Menu",
    viewPermission: "menu.view",
    managePermission: "menu.edit",
    searchColumns: ["name", "slug", "tags", "cuisine"],
    orderBy: { column: "sortOrder", dir: "asc" },
    defaults: { foodType: "veg", spiceLevel: "medium", taxRate: 5, prepTimeMinutes: 20, servingSize: "1 serving", isAvailable: true, isDemoData: false },
    softDelete: true,
    exportable: true,
    moneyFields: ["basePrice", "mrp"],
    fields: [
      { key: "name", label: "Dish name", type: "text", required: true, inTable: true },
      { key: "slug", label: "Slug", type: "text", help: "Used in the menu URL, e.g. /menu/chicken-biryani" },
      { key: "categoryId", label: "Category", type: "select", optionsFrom: "categories", inTable: true },
      { key: "cuisine", label: "Cuisine", type: "text", inTable: true },
      { key: "shortDescription", label: "Short description", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "ingredients", label: "Ingredients", type: "textarea" },
      { key: "allergens", label: "Allergens", type: "text", help: "Informational only: Dairy, Nuts, Gluten, Soy, Egg, Seafood" },
      { key: "imageUrl", label: "Image", type: "image", inTable: true },
      { key: "basePrice", label: "Base price", type: "money", required: true, inTable: true },
      { key: "mrp", label: "MRP (strike-through)", type: "money", inTable: true },
      { key: "taxRate", label: "Tax %", type: "number" },
      { key: "foodType", label: "Food type", type: "select", options: [ { value: "veg", label: "Veg" }, { value: "nonveg", label: "Non-veg" }, { value: "egg", label: "Egg" } ], inTable: true },
      { key: "spiceLevel", label: "Spice level", type: "select", options: [ { value: "mild", label: "Mild" }, { value: "medium", label: "Medium" }, { value: "spicy", label: "Spicy" }, { value: "extra_spicy", label: "Extra spicy" } ] },
      { key: "isJain", label: "Jain option", type: "boolean" },
      { key: "servingSize", label: "Serving size", type: "text" },
      { key: "prepTimeMinutes", label: "Prep time (min)", type: "number", inTable: true },
      { key: "calories", label: "Calories (optional)", type: "number" },
      { key: "isAvailable", label: "Available", type: "select", options: [ { value: "true", label: "Available" }, { value: "false", label: "Currently unavailable" } ], inTable: true },
      { key: "isFeatured", label: "Featured", type: "boolean", inTable: true },
      { key: "isBestseller", label: "Bestseller", type: "boolean" },
      { key: "isPopular", label: "Popular", type: "boolean" },
      { key: "isNew", label: "New", type: "boolean" },
      { key: "isRecommended", label: "Recommended", type: "boolean" },
      { key: "hasCustomization", label: "Customization available", type: "boolean" },
      { key: "tags", label: "Search tags", type: "text", help: "Comma separated: biryani, chicken, spicy" },
      { key: "sortOrder", label: "Sort order", type: "number" },
      { key: "seoTitle", label: "SEO title", type: "text" },
      { key: "seoDescription", label: "SEO description", type: "textarea" },
    ],
  },
  {
    key: "variants",
    label: "Variants",
    singular: "Variant",
    table: menuVariants,
    group: "Menu",
    viewPermission: "menu.view",
    managePermission: "menu.edit",
    searchColumns: ["name"],
    orderBy: { column: "id", dir: "asc" },
    defaults: { isAvailable: true, stock: -1 },
    moneyFields: ["price", "mrp"],
    fields: [
      { key: "menuItemId", label: "Dish", type: "select", optionsFrom: "menu", inTable: true, required: true },
      { key: "name", label: "Variant", type: "text", required: true, inTable: true },
      { key: "price", label: "Price", type: "money", inTable: true, required: true },
      { key: "mrp", label: "MRP", type: "money", inTable: true },
      { key: "stock", label: "Stock (-1 = untracked)", type: "number" },
      { key: "prepTimeMinutes", label: "Prep time (min)", type: "number" },
      { key: "isDefault", label: "Default", type: "boolean", inTable: true },
      { key: "isAvailable", label: "Available", type: "select", options: [ { value: "true", label: "Available" }, { value: "false", label: "Unavailable" } ], inTable: true },
      { key: "sortOrder", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "addons",
    label: "Add-ons",
    singular: "Add-on",
    table: addons,
    group: "Menu",
    viewPermission: "menu.view",
    managePermission: "menu.edit",
    searchColumns: ["name", "groupLabel"],
    orderBy: { column: "sortOrder", dir: "asc" },
    defaults: { isActive: true, isAvailable: true, stock: -1 },
    moneyFields: ["price"],
    exportable: true,
    fields: [
      { key: "name", label: "Name", type: "text", required: true, inTable: true },
      { key: "price", label: "Price", type: "money", inTable: true },
      { key: "groupLabel", label: "Group", type: "text", inTable: true },
      { key: "appliesToCategoryId", label: "Category", type: "select", optionsFrom: "categories" },
      { key: "stock", label: "Stock (-1 = untracked)", type: "number" },
      { key: "isAvailable", label: "Available", type: "select", options: [ { value: "true", label: "Available" }, { value: "false", label: "Unavailable" } ], inTable: true },
      { key: "isActive", label: "Status", type: "select", options: ACTIVE, inTable: true },
      { key: "sortOrder", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    singular: "Ingredient",
    table: inventoryItems,
    group: "Operations",
    viewPermission: "inventory.manage",
    managePermission: "inventory.manage",
    searchColumns: ["name", "supplier"],
    orderBy: { column: "name", dir: "asc" },
    defaults: { unit: "kg", currentStock: 0, lowStockThreshold: 5, isActive: true },
    moneyFields: ["costPerUnit"],
    exportable: true,
    fields: [
      { key: "name", label: "Ingredient", type: "text", required: true, inTable: true },
      { key: "unit", label: "Unit", type: "text", inTable: true },
      { key: "currentStock", label: "Current stock", type: "number", inTable: true },
      { key: "lowStockThreshold", label: "Low stock alert at", type: "number", inTable: true },
      { key: "costPerUnit", label: "Cost per unit", type: "money" },
      { key: "supplier", label: "Supplier", type: "text", inTable: true },
      { key: "isActive", label: "Status", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "coupons",
    label: "Offers & coupons",
    singular: "Coupon",
    table: coupons,
    group: "Marketing",
    viewPermission: "offers.manage",
    managePermission: "offers.manage",
    searchColumns: ["name", "code"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { discountType: "percent", discountValue: 10, perUserLimit: 1, orderTypes: "delivery,pickup,dinein", isActive: true, appliesTo: "all" },
    moneyFields: ["minOrder", "maxDiscount"],
    exportable: true,
    fields: [
      { key: "name", label: "Offer name", type: "text", required: true, inTable: true },
      { key: "code", label: "Coupon code", type: "text", required: true, inTable: true },
      { key: "discountType", label: "Type", type: "select", options: [ { value: "percent", label: "Percentage" }, { value: "fixed", label: "Fixed amount" }, { value: "free_delivery", label: "Free delivery" } ], inTable: true },
      { key: "discountValue", label: "Value (% or ₹)", type: "number", inTable: true, help: "For percentage use 10 for 10%. For fixed, the amount in rupees." },
      { key: "minOrder", label: "Minimum order", type: "money" },
      { key: "maxDiscount", label: "Maximum discount", type: "money" },
      { key: "appliesTo", label: "Applies to", type: "select", options: [ { value: "all", label: "Whole order" }, { value: "category", label: "Category" }, { value: "item", label: "Specific dish" } ] },
      { key: "categoryId", label: "Category", type: "select", optionsFrom: "categories" },
      { key: "menuItemId", label: "Dish", type: "select", optionsFrom: "menu" },
      { key: "startsAt", label: "Starts at", type: "datetime" },
      { key: "endsAt", label: "Ends at", type: "datetime" },
      { key: "usageLimit", label: "Total usage limit (0 = unlimited)", type: "number" },
      { key: "perUserLimit", label: "Per customer limit", type: "number" },
      { key: "usedCount", label: "Used", type: "number", readOnly: true, inTable: true },
      { key: "firstOrderOnly", label: "First order only", type: "boolean" },
      { key: "daysOfWeek", label: "Days (Mon,Tue...)", type: "text", help: "Leave blank for all days" },
      { key: "startTime", label: "Happy hour start", type: "text", help: "24h format e.g. 16:00" },
      { key: "endTime", label: "Happy hour end", type: "text", help: "24h format e.g. 18:00" },
      { key: "orderTypes", label: "Order types", type: "text", help: "delivery,pickup,dinein" },
      { key: "isActive", label: "Status", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "delivery-zones",
    label: "Delivery zones",
    singular: "Zone",
    table: deliveryZones,
    group: "Operations",
    viewPermission: "delivery.view",
    managePermission: "settings.manage",
    searchColumns: ["name", "pincodes"],
    orderBy: { column: "sortOrder", dir: "asc" },
    defaults: { isActive: true, minKm: 0, maxKm: 3 },
    moneyFields: ["fee", "minOrder", "extraPerKm"],
    exportable: true,
    fields: [
      { key: "name", label: "Zone name", type: "text", required: true, inTable: true },
      { key: "minKm", label: "From (km)", type: "number", inTable: true },
      { key: "maxKm", label: "To (km)", type: "number", inTable: true },
      { key: "fee", label: "Delivery fee", type: "money", inTable: true },
      { key: "minOrder", label: "Minimum order", type: "money", inTable: true },
      { key: "extraPerKm", label: "Extra per km", type: "money" },
      { key: "pincodes", label: "Pincodes (comma separated)", type: "text", help: "Used when coordinates are unavailable" },
      { key: "isActive", label: "Status", type: "select", options: ACTIVE, inTable: true },
      { key: "sortOrder", label: "Sort order", type: "number" },
    ],
  },
  {
    key: "tables",
    label: "Tables & QR",
    singular: "Table",
    table: restaurantTables,
    group: "Operations",
    viewPermission: "tables.manage",
    managePermission: "tables.manage",
    searchColumns: ["tableNumber", "code", "section"],
    orderBy: { column: "id", dir: "asc" },
    defaults: { capacity: 4, section: "Ground Floor", status: "available", isActive: true },
    fields: [
      { key: "tableNumber", label: "Table number", type: "text", required: true, inTable: true },
      { key: "code", label: "QR code token", type: "text", required: true, inTable: true, help: "Used in /table/{token}" },
      { key: "capacity", label: "Seating capacity", type: "number", inTable: true },
      { key: "section", label: "Floor / section", type: "text", inTable: true },
      { key: "status", label: "Status", type: "select", options: [ { value: "available", label: "Available" }, { value: "occupied", label: "Occupied" }, { value: "reserved", label: "Reserved" }, { value: "cleaning", label: "Cleaning" }, { value: "maintenance", label: "Maintenance" } ], inTable: true },
      { key: "isActive", label: "Active", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "reservations",
    label: "Reservations",
    singular: "Reservation",
    table: reservations,
    group: "Guests",
    viewPermission: "reservations.manage",
    managePermission: "reservations.manage",
    searchColumns: ["name", "phone", "code"],
    orderBy: { column: "date", dir: "desc" },
    defaults: { guests: 2, status: "requested" },
    exportable: true,
    fields: [
      { key: "code", label: "Code", type: "text", readOnly: true, inTable: true },
      { key: "name", label: "Guest name", type: "text", required: true, inTable: true },
      { key: "phone", label: "Phone", type: "text", required: true, inTable: true },
      { key: "email", label: "Email", type: "text" },
      { key: "date", label: "Date", type: "date", required: true, inTable: true },
      { key: "time", label: "Time", type: "text", required: true, inTable: true },
      { key: "guests", label: "Guests", type: "number", inTable: true },
      { key: "tableId", label: "Assign table", type: "select", optionsFrom: "tables", inTable: true },
      { key: "status", label: "Status", type: "select", options: [ { value: "requested", label: "Requested" }, { value: "confirmed", label: "Confirmed" }, { value: "rejected", label: "Rejected" }, { value: "cancelled", label: "Cancelled" }, { value: "arrived", label: "Arrived" }, { value: "completed", label: "Completed" }, { value: "no_show", label: "No show" } ], inTable: true },
      { key: "specialRequest", label: "Special request", type: "textarea" },
      { key: "adminNote", label: "Internal note", type: "textarea" },
    ],
  },
  {
    key: "customers",
    label: "Customers",
    singular: "Customer",
    table: users,
    group: "Guests",
    viewPermission: "customers.view",
    managePermission: "settings.manage",
    searchColumns: ["name", "email", "phone"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { status: "active" },
    softDelete: true,
    exportable: true,
    fields: [
      { key: "name", label: "Name", type: "text", required: true, inTable: true },
      { key: "email", label: "Email", type: "text", required: true, inTable: true },
      { key: "phone", label: "Phone", type: "text", inTable: true },
      { key: "status", label: "Status", type: "select", options: [ { value: "active", label: "Active" }, { value: "blocked", label: "Blocked" } ], inTable: true },
      { key: "emailVerified", label: "Email verified", type: "boolean", inTable: true },
      { key: "phoneVerified", label: "Phone verified", type: "boolean" },
      { key: "lastLoginAt", label: "Last login", type: "datetime", readOnly: true, inTable: true },
    ],
  },
  {
    key: "reviews",
    label: "Reviews",
    singular: "Review",
    table: reviews,
    group: "Marketing",
    viewPermission: "reviews.manage",
    managePermission: "reviews.manage",
    searchColumns: ["customerName", "comment", "title"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { status: "approved", rating: 5, isDemoData: false },
    exportable: true,
    fields: [
      { key: "customerName", label: "Customer", type: "text", required: true, inTable: true },
      { key: "rating", label: "Rating", type: "number", inTable: true },
      { key: "title", label: "Title", type: "text" },
      { key: "comment", label: "Review", type: "textarea", inTable: true },
      { key: "status", label: "Status", type: "select", options: [ { value: "pending", label: "Pending" }, { value: "approved", label: "Approved" }, { value: "hidden", label: "Hidden" } ], inTable: true },
      { key: "adminResponse", label: "Restaurant response", type: "textarea" },
      { key: "isVerified", label: "Verified order", type: "boolean" },
    ],
  },
  {
    key: "refunds",
    label: "Refunds",
    singular: "Refund",
    table: refunds,
    group: "Payments",
    viewPermission: "orders.refund",
    managePermission: "orders.refund",
    searchColumns: ["refundCode", "reason"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { status: "pending", method: "original" },
    moneyFields: ["amount"],
    creatable: false,
    exportable: true,
    fields: [
      { key: "refundCode", label: "Refund ID", type: "text", readOnly: true, inTable: true },
      { key: "orderId", label: "Order", type: "number", readOnly: true, inTable: true },
      { key: "amount", label: "Amount", type: "money", inTable: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "method", label: "Method", type: "select", options: [ { value: "original", label: "Original payment method" }, { value: "cash", label: "Cash" }, { value: "credit", label: "Store credit" } ] },
      { key: "status", label: "Status", type: "select", options: [ { value: "pending", label: "Refund Pending" }, { value: "initiated", label: "Refund Initiated" }, { value: "completed", label: "Refund Completed" }, { value: "failed", label: "Refund Failed" } ], inTable: true },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "media",
    label: "Media library",
    singular: "Image",
    table: media,
    group: "Content",
    viewPermission: "content.manage",
    managePermission: "content.manage",
    searchColumns: ["title", "altText", "section", "category"],
    orderBy: { column: "sortOrder", dir: "asc" },
    defaults: { category: "food", isActive: true },
    fields: [
      { key: "url", label: "Image", type: "image", required: true, inTable: true },
      { key: "title", label: "Title", type: "text", inTable: true },
      { key: "altText", label: "Alt text", type: "text", help: "Describe the image for accessibility and SEO" },
      { key: "category", label: "Category", type: "select", options: [ { value: "food", label: "Food" }, { value: "drinks", label: "Drinks" }, { value: "interior", label: "Interior" }, { value: "exterior", label: "Exterior" }, { value: "events", label: "Events" }, { value: "kitchen", label: "Kitchen" }, { value: "other", label: "Other" } ], inTable: true },
      { key: "section", label: "Website section", type: "text", inTable: true, help: "e.g. Homepage Hero, Featured Food, About, Gallery" },
      { key: "sortOrder", label: "Sort order", type: "number" },
      { key: "isActive", label: "Visible", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "homepage",
    label: "Homepage sections",
    singular: "Section",
    table: homepageSections,
    group: "Content",
    viewPermission: "content.manage",
    managePermission: "content.manage",
    searchColumns: ["key", "title"],
    orderBy: { column: "position", dir: "asc" },
    defaults: { isActive: true, position: 0 },
    fields: [
      { key: "key", label: "Key", type: "text", required: true, inTable: true },
      { key: "title", label: "Heading", type: "text", required: true, inTable: true },
      { key: "subtitle", label: "Sub heading", type: "text", inTable: true },
      { key: "body", label: "Body copy", type: "textarea" },
      { key: "imageUrl", label: "Image", type: "image", inTable: true },
      { key: "ctaLabel", label: "Button label", type: "text" },
      { key: "ctaHref", label: "Button link", type: "text" },
      { key: "secondaryCtaLabel", label: "Secondary button label", type: "text" },
      { key: "secondaryCtaHref", label: "Secondary button link", type: "text" },
      { key: "position", label: "Position", type: "number", inTable: true },
      { key: "isActive", label: "Visible", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "legal-pages",
    label: "Legal pages",
    singular: "Page",
    table: legalPages,
    group: "Content",
    viewPermission: "content.manage",
    managePermission: "content.manage",
    searchColumns: ["title", "slug"],
    orderBy: { column: "id", dir: "asc" },
    defaults: { isPublished: true },
    fields: [
      { key: "slug", label: "Slug", type: "text", required: true, inTable: true },
      { key: "title", label: "Title", type: "text", required: true, inTable: true },
      { key: "content", label: "Content", type: "textarea", inTable: true },
      { key: "isPublished", label: "Published", type: "select", options: ACTIVE, inTable: true },
    ],
  },
  {
    key: "admins",
    label: "Admin users",
    singular: "Admin",
    table: adminUsers,
    group: "Administration",
    viewPermission: "admins.manage",
    managePermission: "admins.manage",
    searchColumns: ["name", "email"],
    orderBy: { column: "id", dir: "asc" },
    defaults: { status: "active" },
    fields: [
      { key: "name", label: "Name", type: "text", required: true, inTable: true },
      { key: "email", label: "Email", type: "text", required: true, inTable: true },
      { key: "phone", label: "Phone", type: "text" },
      { key: "password", label: "Password", type: "password", createOnly: true, help: "Never displayed. Leave blank when editing to keep the current password." },
      { key: "roleId", label: "Role", type: "select", optionsFrom: "roles", inTable: true },
      { key: "isSuperAdmin", label: "Super admin", type: "boolean", inTable: true },
      { key: "status", label: "Status", type: "select", options: ACTIVE, inTable: true },
      { key: "lastLoginAt", label: "Last login", type: "datetime", readOnly: true, inTable: true },
    ],
  },
  {
    key: "roles",
    label: "Roles & permissions",
    singular: "Role",
    table: roles,
    group: "Administration",
    viewPermission: "admins.manage",
    managePermission: "admins.manage",
    searchColumns: ["name", "slug"],
    orderBy: { column: "id", dir: "asc" },
    defaults: {},
    fields: [
      { key: "name", label: "Role name", type: "text", required: true, inTable: true },
      { key: "slug", label: "Slug", type: "text", required: true, inTable: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "permissions", label: "Permissions", type: "permissions", inTable: true },
    ],
  },
  {
    key: "support-tickets",
    label: "Support tickets",
    singular: "Ticket",
    table: supportTickets,
    group: "Guests",
    viewPermission: "support.manage",
    managePermission: "support.manage",
    searchColumns: ["code", "name", "message", "phone"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { status: "open", priority: "normal" },
    creatable: false,
    exportable: true,
    fields: [
      { key: "code", label: "Ticket", type: "text", readOnly: true, inTable: true },
      { key: "orderId", label: "Order", type: "number", readOnly: true, inTable: true },
      { key: "name", label: "Customer", type: "text", inTable: true },
      { key: "phone", label: "Phone", type: "text", inTable: true },
      { key: "category", label: "Issue", type: "select", options: [ { value: "missing_item", label: "Missing item" }, { value: "wrong_item", label: "Wrong item" }, { value: "quality", label: "Quality issue" }, { value: "payment", label: "Payment issue" }, { value: "delivery", label: "Delivery issue" }, { value: "other", label: "Other" } ], inTable: true },
      { key: "message", label: "Message", type: "textarea", inTable: true },
      { key: "priority", label: "Priority", type: "select", options: [ { value: "low", label: "Low" }, { value: "normal", label: "Normal" }, { value: "high", label: "High" } ], inTable: true },
      { key: "status", label: "Status", type: "select", options: [ { value: "open", label: "Open" }, { value: "in_progress", label: "In Progress" }, { value: "resolved", label: "Resolved" }, { value: "closed", label: "Closed" } ], inTable: true },
      { key: "assignedAdminId", label: "Assigned staff", type: "select", optionsFrom: "drivers" },
      { key: "resolutionNotes", label: "Resolution", type: "textarea" },
    ],
  },
  {
    key: "notifications",
    label: "Notifications",
    singular: "Notification",
    table: notifications,
    group: "Operations",
    viewPermission: "orders.view",
    managePermission: "orders.view",
    searchColumns: ["title", "body"],
    orderBy: { column: "id", dir: "desc" },
    defaults: { audience: "admin", type: "info" },
    fields: [
      { key: "audience", label: "Audience", type: "select", options: [ { value: "admin", label: "Admin" }, { value: "customer", label: "Customer" } ], inTable: true },
      { key: "title", label: "Title", type: "text", required: true, inTable: true },
      { key: "body", label: "Message", type: "textarea", inTable: true },
      { key: "link", label: "Link", type: "text" },
      { key: "type", label: "Type", type: "text" },
      { key: "isRead", label: "Read", type: "boolean", inTable: true },
    ],
  },
];

export function getResource(key: string): ResourceDef | undefined {
  return RESOURCES.find((r) => r.key === key);
}

export function tableColumns(def: ResourceDef): Record<string, unknown> {
  return getTableColumns(def.table) as unknown as Record<string, unknown>;
}
